def startMenu():
    print("                        _______ ")
    print("                    ---'   ____) ")
    print("                         (_____) ")
    print("                          (_____)         ROCK")
    print("                          (____) ")
    print("                    ---.__(___) ")

    print("           _______ ")
    print("       ---'   ____)____ ")
    print("                 ______) ")
    print("                 _______)   PAPER")
    print("               _______) ")
    print("       ---.__________) \n")

    print(".\"\".    .\"\",")
    print("|  |   /  /")
    print("|  |  /  /")
    print("|  | /  /")
    print("|  |/  ;-._")
    print("}  ` _/  / ;")
    print("|  /` ) /  /           SCISSORS!!")
    print("| /  /_/\_/\ ")
    print("|/  /      |")
    print("(  ' \ '-  |")
    print("\    `.   /")
    print("|        | ")
    print("|        | ")
    print("----------------------------------------")
    print("----------------------------------------")

    print("Rules")
    print("You start with 5 lives")
    print("If you win you get an extra life.")
    print("If you lose you lose a life.")
    print("----------------------------------------")
    print("To see the rules type 'rules'")
    print("For more info, type 'info'")
    print("----------------------------------------")
    print("At any point type exit to leave the game")
    print("The computer has lives as well.")
    print("Can you beat the computer?")
    print("Good Luck!")
    print("----------------------------------------\n")
